### PR TITLE
Add a version number

### PR DESCRIPTION
**Pull request by BrianEnigma**
If we're going to incorporate updates from the upstream git-fat
repository, we're going to have to keep track of which version that
folks at Elemental are using.

### CODE REVIEW

**Comment by reidab** [comment]
Ideally, I think we'd either move back to actually using the released upstream version of git-fat (and lobby for any custom changes to be merged back there), or migrate everything to the arguably-more-maintained https://git-lfs.github.com

**Comment by BrianEnigma** [comment]
As far as the upstream version goes: in this case, the "elemental-1.0" indicates it's the one we've been using since we started. There is a second branch that is identical to the current upstream master, but with "elemental-1.1" added to differentiate the two. https://github.com/elementaltech/git-fat/tree/upstream_refresh 

No version number or "elemental-1.0" means this version. "elemental-1.1" means the snapshot from upstream's master taken on the last hackday. I don't think we want to tail the upstream master too closely without first evaluating the changes, hence the "elemental-x.y" snapshots.

I'd prefer to make the elemental-1.1 version default, but that version depends on a version of Python we don't have (installed by default) until CentOS 7.

Much more detail on the internal Jive post "git-fat Analysis, Part 2".

**Comment by reidab** [comment]
Got it. In that case, this parallel elemental version number makes a lot of sense. :+1:

**Comment by reidab** [comment]
We may want to add a note to the top of the README mentioning our snapshotting practices, since this is a public repo and most people probably don't want to use our version…

**Pull request merged**
